name: ⚙️ Continuous bootstrap 📦

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 5'
    
jobs:
  bootstrap_and_release:
    name: runimage-bootstrap
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
          filter: "blob:none"
          
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
           tool-cache: false
           android: true
           dotnet: true
           haskell: true
           large-packages: true
           docker-images: true
           swap-storage: true

      - name: Install deps
        run: |
          sudo sh -c 'apt update && apt install qemu-user-static zsync -y'
          sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns <<<0
          docker pull tonistiigi/binfmt:latest
          docker run --privileged --rm tonistiigi/binfmt --uninstall qemu-*
          docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Bootstrap RunImage
        run: |
            set -x ; set -e
            mkdir -p release && cd release||exit 1

            ../main/rim-bootstrap

            rm -f runimage

            echo "\
            -----------------------------------------------------------------------------------------------------------------------------
            * [runimage-x86_64](GHCR Hosted) | [pkg_list-x86_64.txt](GHCR Hosted)
            -----------------------------------------------------------------------------------------------------------------------------
            " > ../RELEASE_NOTE.md

      - name: Generate Zsync
        run: |
           cd release
           zsyncmake runimage-x86_64

      - name: Setup ORAS
        uses: oras-project/setup-oras@v2.0.1
        
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to GHCR using ORAS
        run: |
          cd release
          
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          oras push ghcr.io/$REPO_LC/runimage:continuous \
            ./runimage-x86_64 \
            ./runimage-x86_64.zsync \
            ./pkg_list-x86_64.txt \
            ../RELEASE_NOTE.md
